version: '3.8'

services:
  # Redis 服務
  redis:
    image: "redis:alpine" # 使用輕量的 Redis 映像檔
    container_name: paramount_redis
    ports:
      - "6379:6379" # 將容器的 6379 連接埠映射到主機，方便本地偵錯
    volumes:
      - redis-data:/data # 持久化 Redis 資料

  # Python 爬蟲服務 (舊的 app 服務)
  scraper:
    container_name: paramount_scraper
    build: 
      context: ./scraper # 指向新的 scraper 資料夾
      dockerfile: Dockerfile # Dockerfile 現在在 scraper 資料夾內
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./scraper:/app # 將本地的 scraper 資料夾掛載到容器的 /app

  # Next.js 全端應用服務
  next-app:
    container_name: paramount_viewer
    build:
      context: ./next-app # 指向 next-app 資料夾
      dockerfile: Dockerfile # 指向 Next.js 的 Dockerfile
    depends_on:
      - redis
    ports:
      - "3000:3000" # 將 Next.js 的 3000 port 映射出來
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NEXT_PUBLIC_API_URL=http://localhost:3000/api/posts

volumes:
  redis-data: 